# Generated by Django 4.2.1 on 2023-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Surat')),
            ],
            options={
                'verbose_name': 'Kitoblar',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism')),
                ('number', models.CharField(max_length=13, verbose_name='Raqam')),
                ('age', models.CharField(max_length=2, verbose_name='Yoshi')),
                ('title', models.TextField(verbose_name='Murojat')),
            ],
            options={
                'verbose_name': 'Anketa',
                'verbose_name_plural': 'Anketa',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('title', models.TextField(verbose_name='Matn')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Surat')),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
